mod 'puppet/nginx', '1.0.0' 
mod 'puppetlabs-stdlib', '9.3.0'
mod 'puppetlabs/concat'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker', '9.1.0'
mod 'puppetlabs-apt', '9.1.0'
mod 'puppetlabs-powershell', '6.0.0'
mod 'puppetlabs-reboot', '5.0.0'
